<?php
/**
 * @author     Martin Høgh <mh@mapcentia.com>
 * @copyright  2013-2024 MapCentia ApS
 * @license    http://www.gnu.org/licenses/#AGPL  GNU AFFERO GENERAL PUBLIC LICENSE 3
 *
 */

namespace app\extensions\fkgupload\api;


/**
 * Class Schemata
 * @package app\extensions\fkgupload\api
 */
class Schemata
{
    const string MULTIPOINT = "MULTIPOINT";
    const string MULTILINESTRING = "MULTILINESTRING";
    const string MULTIPOLYGON = "MULTIPOLYGON";

    /**
     * @var array[][]
     */
    static public $schemata = [
        5003 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],

            "ledn_nr" => ["ledn_nr", false, "varchar"],
            "ledn_type_kode" => ["ledn_t_k", false, "int"],
            "klasse_kode" => ["klasse_k", false, "int"],
            "etableringstidspunkt" => ["etabl_tid", false, "varchar"],
            "start_dybde" => ["start_dyb", false, "double precision"],
            "slut_dybde" => ["slut_dyb", false, "double precision"],
            "start_kote" => ["start_kote", false, "double precision"],
            "slut_kote" => ["slut_kote", false, "double precision"],
            "kotesystem_kode" => ["kotesyst_k", false, "int"],
            "fald_promille" => ["fald_prom", false, "double precision"],
            "diameter_mm" => ["diam_mm", false, "int"],
            "diameter_tommer" => ["diam_tomme", false, "double precision"],
            "datakilde_kode" => ["datakild_k", false, "int"],
            "praecision_god" => ["praecis", false, "boolean"],
            "projektnr" => ["projektnr", false, "varchar"],
            "kommentar" => ["kommentar", false, "varchar"],

            "noegle" => ["noegle", false, "varchar"],
            "sagsnr" => ["sagsnr", false, "varchar"],
            "link" => ["link", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "geometri" => ["the_geom", true, "geometry", self::MULTILINESTRING],
        ],

        5011 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],

            "broend_nr" => ["broend_nr", false, "varchar"],
            "broendtype_kode" => ["br_type_k", false, "int"],
            "diameter_mm" => ["diam_mm", false, "int"],
            "diameter_tommer" => ["diam_tomme", false, "double precision"],
            "dybde_udloeb" => ["dybde_ud", false, "int"],
            "kote_udloeb" => ["kote_ud", false, "double precision"],
            "kotesystem_kode" => ["kotesyst_k", false, "int"],
            "datakilde_kode" => ["datakild_k", false, "int"],
            "bemaerkning" => ["bemaerk", false, "varchar"],
            "broend_synlig" => ["broend_syn", false, "boolean"],
            "etableringstidspunkt" => ["etabl_tid", false, "varchar"],
            "praecision_god" => ["praecis", false, "boolean"],

            "noegle" => ["noegle", false, "varchar"],
            "sagsnr" => ["sagsnr", false, "varchar"],
            "link" => ["link", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "geometri" => ["the_geom", true, "geometry", self::MULTIPOINT],
        ],

        5004 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],

            "omr_navn" => ["omr_navn", false, "varchar"],
            "omr_type_kode" => ["omr_type_k", true, "int"],
            "etableringstidspunkt" => ["etabl_tid", false, "varchar"],
            "projektnr" => ["projektnr", false, "varchar"],
            "bemaerkning" => ["bemaerk", false, "varchar"],

            "noegle" => ["noegle", false, "varchar"],
            "sagsnr" => ["sagsnr", false, "varchar"],
            "link" => ["link", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "geometri" => ["the_geom", true, "geometry", self::MULTIPOLYGON],
        ],

        5700 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],

            "forening_type_kode" => ["foren_ty_k", true, "int"],
            "forening_navn" => ["foren_navn", true, "varchar"],
            "lokalpl_nr" => ["lokalpl_nr", false, "varchar"],
            "formand" => ["formand", false, "varchar"],
            "gf_tlf" => ["gf_tlf", false, "int"],
            "gf_mail" => ["gf_mail", false, "varchar"],
            "gf_adr_beskyt_kode" => ["gf_besky_k", false, "varchar"],
            "vedtaegt_kode" => ["vedtaegt_k", false, "int"],
            "sagsnr" => ["sagsnr", false, "varchar"],

            "noegle" => ["noegle", false, "varchar"],
            "link" => ["link", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "cvr_opslag" => ["cvr_opslag", false, "varchar"],
            "geometri" => ["the_geom", true, "geometry", self::MULTIPOLYGON],
        ],
        5701 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],

            "lokaludv_type_kode" => ["Lokalu_t_k", true, "int"],
            "lokaludv_navn" => ["lokalu_n", true, "varchar"],

            "noegle" => ["noegle", false, "varchar"],
            "sagsnr" => ["sagsnr", false, "varchar"],
            "link" => ["link", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "geometri" => ["the_geom", true, "geometry", self::MULTIPOLYGON],
        ],
        5702 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],

            "skorstenf_distrikt_nr" => ["skor_di_nr", false, "int"],
            "skorstenf_distrikt_navn" => ["skor_di_na", false, "varchar"],
            "gyldig_fra" => ["gyldig_fra", true, "date"],
            "gyldig_til" => ["gyldig_til", false, "date"],
            "skorstensfejer_firma" => ["skor_firma", true, "varchar"],


            "noegle" => ["noegle", false, "varchar"],
            "sagsnr" => ["sagsnr", false, "varchar"],
            "link" => ["link", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "cvr_opslag" => ["cvr_opslag", false, "varchar"],
            "geometri" => ["the_geom", true, "geometry", self::MULTIPOLYGON],
        ],
        5705 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],

            "forpagter_navn" => ["forpagt_na", true, "varchar"],
            "forpagter_formaal" => ["forpagt_fm", false, "varchar"],
            "udlejning_kode" => ["udlejnin_k", true, "int"],
            "landbrug_kode" => ["Landbrug_k", true, "int"],

            "noegle" => ["noegle", false, "varchar"],
            "sagsnr" => ["sagsnr", false, "varchar"],
            "link" => ["link", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "cvr_opslag" => ["cvr_opslag", false, "varchar"],
            "geometri" => ["the_geom", true, "geometry", self::MULTIPOLYGON],
        ],
        5706 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],

            "havn_nr" => ["havn_nr", false, "int"],
            "havn_navn" => ["havn_navn", false, "varchar"],
            "havne_type_kode" => ["havne_ty_k", true, "int"],
            "ejer_admin" => ["ejer_admin", false, "varchar"],

            "noegle" => ["noegle", false, "varchar"],
            "link" => ["link", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "cvr_opslag" => ["cvr_opslag", false, "varchar"],
            "geometri" => ["the_geom", true, "geometry", self::MULTIPOLYGON],
        ],
        5707 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],

            "udstyk_navn" => ["udstyk_na", true, "varchar"],
            "grund_type_kode" => ["grund_ty_k", true, "int"],
            "salg_status_kode" => ["salg_sta_k", true, "int"],
            "pris" => ["pris", false, "int"],
            "mindste_pris" => ["mind_pris", false, "int"],
            "kvm_pris" => ["kvm_pris", false, "double precision"],
            "kontakt_oplys" => ["kontak_opl", false, "varchar"],
            "grundareal" => ["grundareal", false, "int"],
            "bygningareal" => ["bygn_areal", false, "int"],
            "budfrist_slut" => ["budfr_slut", false, "date"],

            "vejkode" => ["vejkode", false, "int"],
            "cvf_vejkode" => ["cvf_vejkode", false, "varchar"],
            "husnr" => ["husnr", false, "varchar"],
            "postnr" => ["postnr", false, "int"],
            "adr_id" => ["adr_id", false, "uuid"],

            "noegle" => ["noegle", false, "varchar"],
            "sagsnr" => ["sagsnr", false, "varchar"],
            "link" => ["link", false, "varchar"],
            "note" => ["note", false, "varchar"],

            "foto_link" => ["foto_link", false, "varchar"],
            "foto_link1" => ["foto_link1", false, "varchar"],
            "foto_link2" => ["foto_link2", false, "varchar"],
            "foto_link3" => ["foto_link3", false, "varchar"],

            "geometri" => ["the_geom", true, "geometry", self::MULTIPOLYGON],
        ],
        5710 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],

            "udd_distrikt_nr" => ["udd_dis_nr", false, "int"],
            "udd_distrikt_navn" => ["udd_dis_na", false, "varchar"],
            "udd_distrikt_type_kode" => ["udd_d_ty_k", true, "int"],
            "starttrin_kode" => ["strtr_kode", false, "int"],
            "sluttrin_kode" => ["slutr_kode", false, "int"],
            "udd_hovedomr_nr" => ["udd_omr_nr", false, "int"],
            "udd_hovedomr_navn" => ["udd_omr_na", false, "varchar"],
            "udd_delomr_nr" => ["udd_del_nr", false, "int"],
            "udd_delomr_navn" => ["udd_del_na", false, "varchar"],

            "noegle" => ["noegle", false, "varchar"],
            "sagsnr" => ["sagsnr", false, "varchar"],
            "link" => ["link", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "geometri" => ["the_geom", true, "geometry", self::MULTIPOLYGON],
        ],
        5711 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],

            "an_distrikt_nr" => ["an_dis_nr", false, "int"],
            "an_distrikt_navn" => ["an_dis_na", false, "varchar"],
            "an_distrikt_type_kode" => ["an_dis_t_k", false, "int"],

            "noegle" => ["noegle", false, "varchar"],
            "sagsnr" => ["sagsnr", false, "varchar"],
            "link" => ["link", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "geometri" => ["the_geom", true, "geometry", self::MULTIPOLYGON],
        ],
        5712 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],

            "plej_distrikt_nr" => ["pl_dis_nr", false, "int"],
            "plej_distrikt_navn" => ["pl_dis_na", false, "varchar"],
            "plej_distrikt_type_kode" => ["pl_dis_ty_k", false, "int"],
            "plej_distrikt_dag" => ["plej_d_dag", false, "varchar"],
            "plej_distrikt_aften" => ["plej_d_aft", false, "varchar"],
            "plej_distrikt_nat" => ["plej_d_nat", false, "varchar"],

            "noegle" => ["noegle", false, "varchar"],
            "sagsnr" => ["sagsnr", false, "varchar"],
            "link" => ["link", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "geometri" => ["the_geom", true, "geometry", self::MULTIPOLYGON],
        ],
        5713 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],

            "prog_distrikt_nr" => ["pro_dis_nr", false, "int"],
            "prog_distrikt_navn" => ["pro_dis_na", false, "varchar"],
            "prog_distrikt_type_kode" => ["pro_di_ty_k", false, "int"],

            "noegle" => ["noegle", false, "varchar"],
            "sagsnr" => ["sagsnr", false, "varchar"],
            "link" => ["link", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "geometri" => ["the_geom", true, "geometry", self::MULTIPOLYGON],
        ],
        5715 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],

            "botilbud_type_kode" => ["botilbud_k", true, "int"],
            "ejerstatus_kode" => ["ejerstat_k", false, "int"],
            "botilbud_navn" => ["botilbu_na", false, "varchar"],
            "vejkode" => ["vejkode", false, "int"],
            "cvf_vejkode" => ["cvf_vejkode", false, "varchar"],
            "husnr" => ["husnr", false, "varchar"],
            "postnr" => ["postnr", false, "int"],
            "adr_id" => ["adr_id", false, "uuid"],

            "noegle" => ["noegle", false, "varchar"],
            "link" => ["link", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "geometri" => ["the_geom", true, "geometry", self::MULTIPOINT],
        ],
        5716 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],

            "service_type_kode" => ["service_k", true, "int"],
            "ejerstatus_kode" => ["ejerstat_k", false, "int"],
            "servicetilbud_navn" => ["service_na", false, "varchar"],
            "vejkode" => ["vejkode", false, "int"],
            "cvf_vejkode" => ["cvf_vejkode", false, "varchar"],
            "husnr" => ["husnr", false, "varchar"],
            "postnr" => ["postnr", false, "int"],
            "adr_id" => ["adr_id", false, "uuid"],

            "noegle" => ["noegle", false, "varchar"],
            "link" => ["link", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "geometri" => ["the_geom", true, "geometry", self::MULTIPOINT],
        ],
        5717 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],

            "part_type_kode" => ["part_ty_k", true, "int"],
            "part_navn" => ["part_navn", true, "varchar"],
            "part_formand" => ["p_formand", false, "varchar"],
            "part_formand_tlf" => ["pform_tlf", false, "int"],
            "part_formand_mail" => ["pform_mail", false, "varchar"],
            "adr_beskyt_kode" => ["adr_b_kode", false, "varchar"],

            "vejkode" => ["vejkode", false, "int"],
            "cvf_vejkode" => ["cvf_vejkode", false, "varchar"],
            "husnr" => ["husnr", false, "varchar"],
            "postnr" => ["postnr", false, "int"],

            "noegle" => ["noegle", false, "varchar"],
            "sagsnr" => ["sagsnr", false, "varchar"],
            "link" => ["link", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "cvr_opslag" => ["cvr_opslag", false, "varchar"],
            "adr_id" => ["adr_id", false, "uuid"],
            "geometri" => ["the_geom", true, "geometry", self::MULTIPOLYGON],
        ],

        5800 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],
            "noegle" => ["noegle", false, "varchar"],
            "note" => ["note", false, "varchar"],

            "facil_ty_k" => ["facil_ty_k", true, "int"],
            "navn" => ["navn", false, "varchar"],
            "beskrivels" => ["beskrivels", false, "varchar"],
            "lang_beskr" => ["lang_beskr", false, "varchar"],
            "uk_k_beskr" => ["uk_k_beskr", false, "varchar"],
            "uk_l_beskr" => ["uk_l_beskr", false, "varchar"],
            "d_k_beskr" => ["d_k_beskr", false, "varchar"],
            "d_l_beskr" => ["d_l_beskr", false, "varchar"],
            "ansvar_org" => ["ansvar_org", false, "varchar"],
            "kontak_ved" => ["kontak_ved", false, "varchar"],

            "handicap_k" => ["handicap_k", false, "int"], // Felt defineret under: 4.1

            "saeson_k" => ["saeson_k", false, "int"],
            "saeson_st" => ["saeson_st", false, "date"],
            "saeson_sl" => ["saeson_sl", false, "date"],
            "doegnaab_k" => ["doegnaab_k", false, "int"],
            "vandhane_k" => ["vandhane_k", false, "int"],
            "bemand_k" => ["bemand_k", false, "int"],
            "betaling_k" => ["betaling_k", false, "int"],
            "book_k" => ["book_k", false, "int"],
            "antal_pl" => ["antal_pl", false, "int"],
            "adr_id" => ["adr_id", false, "uuid"],

            "foto_link" => ["foto_link", false, "varchar"],
            "foto_link1" => ["foto_link1", false, "varchar"],
            "foto_link2" => ["foto_link2", false, "varchar"],
            "foto_link3" => ["foto_link3", false, "varchar"],

            "folder_k" => ["folder_k", false, "int"],
            "folde_link" => ["folde_link", false, "varchar"],
            "foldelink1" => ["foldelink1", false, "varchar"],
            "foldelink2" => ["foldelink2", false, "varchar"],
            "foldelink3" => ["foldelink3", false, "varchar"],

            "filmlink" => ["filmlink", false, "varchar"],
            "filmlink1" => ["filmlink1", false, "varchar"],
            "filmlink2" => ["filmlink3", false, "varchar"],
            "filmlink3" => ["filmlink3", false, "varchar"],

            "geofafoto" => ["geofafoto", false, "varchar"],
            "geofafoto1" => ["geofafoto1", false, "varchar"],
            "geofafoto2" => ["geofafoto2", false, "varchar"],
            "geofafoto3" => ["geofafoto3", false, "varchar"],

            "link" => ["link", false, "varchar"],
            "link1" => ["link1", false, "varchar"],
            "link2" => ["link2", false, "varchar"],
            "link3" => ["link3", false, "varchar"],

            "ansva_v_k" => ["ansva_v_k", false, "int"], // Felt defineret under: 4.1

            "geometri" => ["the_geom", true, "geometry", self::MULTIPOINT],

            "saeson_bem" => ["saeson_bem", false, "varchar"],
            "vejkode" => ["vejkode", false, "int"],
            "cvf_vejkode" => ["cvf_vejkode", false, "varchar"],
            "husnr" => ["husnr", false, "varchar"],
            "postnr" => ["postnr", false, "int"],
            "kvalitet_k" => ["kvalitet_k", false, "int"],

            "tilgaeng_opl" => ["tilgaeng_o", false, "jsonb"],
            "tilgaeng_beskriv" => ["tilgaeng_b", false, "varchar"],
            "bookinglink" => ["book_link", false, "varchar"],
        ],
        5801 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],
            "noegle" => ["noegle", false, "varchar"],
            "note" => ["note", false, "varchar"],

            "facil_ty_k" => ["facil_ty_k", true, "int"],
            "navn" => ["navn", false, "varchar"],
            "beskrivels" => ["beskrivels", false, "varchar"],
            "lang_beskr" => ["lang_beskr", false, "varchar"],
            "uk_k_beskr" => ["uk_k_beskr", false, "varchar"],
            "uk_l_beskr" => ["uk_l_beskr", false, "varchar"],
            "d_k_beskr" => ["d_k_beskr", false, "varchar"],
            "d_l_beskr" => ["d_l_beskr", false, "varchar"],
            "ansvar_org" => ["ansvar_org", false, "varchar"],
            "kontak_ved" => ["kontak_ved", false, "varchar"],

            "handicap_k" => ["handicap_k", false, "int"], // Felt defineret under: 4.1

            "saeson_k" => ["saeson_k", false, "int"],
            "saeson_st" => ["saeson_st", false, "date"],
            "saeson_sl" => ["saeson_sl", false, "date"],
            "doegnaab_k" => ["doegnaab_k", false, "int"],
            "vandhane_k" => ["vandhane_k", false, "int"],
            "bemand_k" => ["bemand_k", false, "int"],
            "betaling_k" => ["betaling_k", false, "int"],
            "book_k" => ["book_k", false, "int"],
            "antal_pl" => ["antal_pl", false, "int"],
            "adr_id" => ["adr_id", false, "uuid"],

            "foto_link" => ["foto_link", false, "varchar"],
            "foto_link1" => ["foto_link1", false, "varchar"],
            "foto_link2" => ["foto_link2", false, "varchar"],
            "foto_link3" => ["foto_link3", false, "varchar"],

            "folder_k" => ["folder_k", false, "int"],
            "folde_link" => ["folde_link", false, "varchar"],
            "foldelink1" => ["foldelink1", false, "varchar"],
            "foldelink2" => ["foldelink2", false, "varchar"],
            "foldelink3" => ["foldelink3", false, "varchar"],

            "filmlink" => ["filmlink", false, "varchar"],
            "filmlink1" => ["filmlink1", false, "varchar"],
            "filmlink2" => ["filmlink2", false, "varchar"],
            "filmlink3" => ["filmlink3", false, "varchar"],

            "geofafoto" => ["geofafoto", false, "varchar"],
            "geofafoto1" => ["geofafoto1", false, "varchar"],
            "geofafoto2" => ["geofafoto2", false, "varchar"],
            "geofafoto3" => ["geofafoto3", false, "varchar"],

            "link" => ["link", false, "varchar"],
            "link1" => ["link1", false, "varchar"],
            "link2" => ["link2", false, "varchar"],
            "link3" => ["ink3", false, "varchar"],

            "ansva_v_k" => ["ansva_v_k", false, "int"], // Felt defineret under: 4.1

            "geometri" => ["the_geom", true, "geometry", self::MULTIPOLYGON],

            "saeson_bem" => ["saeson_bem", false, "varchar"],
            "vejkode" => ["vejkode", false, "int"],
            "cvf_vejkode" => ["cvf_vejkode", false, "varchar"],
            "husnr" => ["husnr", false, "varchar"],
            "postnr" => ["postnr", false, "int"],
            "kvalitet_k" => ["kvalitet_k", false, "int"],
            "tilgaeng_opl" => ["tilgaeng_o", false, "jsonb"],
            "tilgaeng_beskriv" => ["tilgaeng_b", false, "varchar"],
            "bookinglink" => ["book_link", false, "varchar"],
        ],
        5802 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],
            "noegle" => ["noegle", false, "varchar"],
            "note" => ["note", false, "varchar"],

            "rute_ty_k" => ["rute_ty_k", true, "int"],
            "rute_uty_k" => ["rute_uty_k", false, "int"],

            "navn" => ["navn", false, "varchar"],
            "navndels" => ["navndels", false, "varchar"],
            "straekn_nr" => ["straekn_nr", false, "varchar"],

            "afm_rute_k" => ["afm_rute_k", false, "int"],
            "laengde" => ["laengde", false, "numeric"],

            "beskrivels" => ["beskrivels", false, "varchar"],
            "lang_beskr" => ["lang_beskr", false, "varchar"],
            "uk_k_beskr" => ["uk_k_beskr", false, "varchar"],
            "uk_l_beskr" => ["uk_l_beskr", false, "varchar"],
            "d_k_beskr" => ["d_k_beskr", false, "varchar"],
            "d_l_beskr" => ["d_l_beskr", false, "varchar"],
            "ansvar_org" => ["ansvar_org", false, "varchar"],
            "kontak_ved" => ["kontak_ved", false, "varchar"],
            "betaling_k" => ["betaling_k", false, "int"],

            "belaegn_k" => ["belaegn_k", false, "int"], // Felt defineret under: 4.1
            "handicap_k" => ["handicap_k", false, "int"], // Felt defineret under: 4.1
            "ansva_v_k" => ["ansva_v_k", false, "int"], // Felt defineret under: 4.1

            "startpkt_x" => ["startpkt_x", false, "int"],
            "startpkt_y" => ["startpkt_y", false, "int"],
            "slutpkt_x" => ["slutpkt_x", false, "int"],
            "slutpkt_y" => ["slutpkt_y", false, "int"],
            "svaerhed_k" => ["svaerhed_k", false, "int"],
            "obs" => ["obs", false, "varchar"],
            "kategori_k" => ["kategori_k", false, "int"],
            "certifi_k" => ["certifi_k", false, "int"],
            "hierarki_k" => ["hierarki_k", false, "int"],
            "gpx_link" => ["gpx_link", false, "varchar"],
            "adr_id" => ["adr_id", false, "uuid"],

            "foto_link" => ["foto_link", false, "varchar"],
            "foto_link1" => ["foto_link1", false, "varchar"],
            "foto_link2" => ["foto_link2", false, "varchar"],
            "foto_link3" => ["foto_link3", false, "varchar"],

            "folder_k" => ["folder_k", false, "int"],
            "folde_link" => ["folde_link", false, "varchar"],
            "foldelink1" => ["foldelink1", false, "varchar"],
            "foldelink2" => ["foldelink2", false, "varchar"],
            "foldelink3" => ["foldelink3", false, "varchar"],

            "filmlink" => ["filmlink", false, "varchar"],
            "filmlink1" => ["filmlink1", false, "varchar"],
            "filmlink2" => ["filmlink2", false, "varchar"],
            "filmlink3" => ["filmlink3", false, "varchar"],

            "geofafoto" => ["geofafoto", false, "varchar"],
            "geofafoto1" => ["geofafoto1", false, "varchar"],
            "geofafoto2" => ["geofafoto2", false, "varchar"],
            "geofafoto3" => ["geofafoto3", false, "varchar"],

            "link" => ["link", false, "varchar"],
            "link1" => ["link1", false, "varchar"],
            "link2" => ["link2", false, "varchar"],
            "link3" => ["ink3", false, "varchar"],

            "geometri" => ["the_geom", true, "geometry", self::MULTILINESTRING],

            "saeson_bem" => ["saeson_bem", false, "varchar"],
            "vejkode" => ["vejkode", false, "int"],
            "cvf_vejkode" => ["cvf_vejkode", false, "varchar"],
            "husnr" => ["husnr", false, "varchar"],
            "postnr" => ["postnr", false, "int"],
            "kvalitet_k" => ["kvalitet_k", false, "int"],
            "tilgaeng_opl" => ["tilgaeng_o", false, "jsonb"],
            "tilgaeng_beskriv" => ["tilgaeng_b", false, "varchar"],
            "danmarksnaturstier" => ["dknatursti", false, "bool"],
            "rutefarve_k" => ["rut_farv_k", false, "int"],
        ],

        5607 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],
            "noegle" => ["noegle", false, "varchar"],
            "note" => ["note", false, "varchar"],

            "adr_id" => ["adr_id", false, "uuid"],
            "ansvar_org" => ["ansvar_org", false, "varchar"],
            "antal_ladepunkter" => ["ladepkt", false, "int"],
            "anvendelsesgrad_kwh" => ["anvgr_kWh", false, "int"],
            "driftstart_fra" => ["drift_fra", false, "date"],
            "foto_link" => ["link", false, "varchar"],
            "foto_link1" => ["link", false, "varchar"],
            "foto_link2" => ["link", false, "varchar"],
            "foto_link3" => ["link", false, "varchar"],
            "effekt_type_kode" => ["effekt_k", false, "int"],
            "ejer_ladefacilitet" => ["ejer", false, "varchar"],
            "gyldig_fra" => ["gyldig_fra", false, "date"],
            "gyldig_til" => ["gyldig_til", false, "date"],
            "internationalt_id" => ["int_id", false, "varchar"],
            "internationalt_id1" => ["int_id1", false, "varchar"],
            "internationalt_id2" => ["int_id2", false, "varchar"],
            "internationalt_id3" => ["int_id3", false, "varchar"],
            "internationalt_id4" => ["int_id4", false, "varchar"],
            "internationalt_id5" => ["int_id5", false, "varchar"],
            "kontak_ved" => ["kontak_ved", false, "varchar"],
            "ladefacilitet_type_kode" => ["lade_ty_k", true, "int"],
            "link" => ["link", false, "varchar"],
            "link1" => ["link", false, "varchar"],
            "link2" => ["link", false, "varchar"],
            "link3" => ["link", false, "varchar"],
            "link4" => ["link", false, "varchar"],
            "sagsnr" => ["sagsnr", false, "varchar"],
            "planstatus_kode" => ["planstat_k", false, "int"],

            "operatoer_ladefacilitet" => ["operatoer", false, "varchar"],
            "udbyder_ladefacilitet" => ["udbyder", false, "varchar"],
            "stiktype" => ["stiktype", false, "varchar"],
            "tilgaengelighed_type_kode" => ["tilgae_ty_k", false, "int"],
            "omraade_navn" => ["omr_navn", false, "varchar"],

            "geometri" => ["the_geom", true, "geometry", self::MULTIPOINT],
        ],
        5608 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],
            "noegle" => ["noegle", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "link" => ["link", false, "varchar"],

            "planstatus_kode" => ["planstat_k", false, "int"],
            "beliggenhedskommune" => ["belig_kom", false, "int"],

            "id_cykelknudepkt" => ["id_cykelkp", true, "varchar"],
            "nodenumber" => ["nodenumber", false, "varchar"],
            "ismain" => ["ismain", false, "bool"],
            "deadend" => ["deadend", true, "bool"],
            "refmain" => ["refmain", false, "varchar"],
            "afm_cykelknudepkt" => ["afm_kpkt", true, "bool"],

            "geometri" => ["the_geom", true, "geometry", self::MULTIPOINT],
        ],
        5609 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],
            "noegle" => ["noegle", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "link" => ["link", false, "varchar"],

            "planstatus_kode" => ["planstat_k", false, "int"],
            "beliggenhedskommune" => ["belig_kom", false, "int"],

            "id_cykelknudepunktsstraekning" => ["id_cykelks", true, "varchar"],
            "length" => ["length", false, "double precision"],
            "privatenot" => ["privatenot", true, "bool"],
            "surfacenot" => ["surfacenot", true, "bool"],
            "onewaynot" => ["onewaynot", true, "bool"],

            "geometri" => ["the_geom", true, "geometry", self::MULTILINESTRING],
        ],
        5610 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],
            "noegle" => ["noegle", false, "varchar"],
            "note" => ["note", false, "varchar"],

            "planstatus_kode" => ["planstat_k", false, "int"],

            "rute_type_kode" => ["rutetype_k", false, "int"],
            "rute_undertype_kode" => ["rute_u_t_k", false, "int"],
            "planlaegningskort_type_kode" => ["kort_type_k", false, "int"],
            "rute_navn" => ["rute_navn", false, "varchar"],
            "rute_nr" => ["rute_nr", false, "varchar"],
            "rute_beskrivelse" => ["rute_beskrivelse", false, "varchar"],
            "plan_type_kode" => ["plantype_k", false, "int"],
            "finansiering_kode" => ["finans_k", false, "int"],
            "aarstal" => ["aarstal", false, "int"],
            "beloeb" => ["beloeb", false, "int"],
            "prioritering_kode" => ["prior_k", false, "int"],
            "potentiale" => ["potentiale", false, "varchar"],
            "eksisterende_kode" => ["eksis_k", false, "int"],
            "faelleskommunalt_projekt_kode" => ["falles_p_k", false, "boolean"],

            "geometri" => ["the_geom", true, "geometry", self::MULTILINESTRING],
        ],
        5600 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],
            "noegle" => ["noegle", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "link" => ["link", false, "varchar"],

            "vinterklasse_kode" => ["vi_klas_k", true, "int"],
            "adm_vejnr" => ["adm_vejnr", false, "int"],
            "frakm" => ["frakm", false, "int"],
            "fram" => ["fram", false, "int"],
            "tilkm" => ["tilkm", false, "int"],
            "tilm" => ["tilm", false, "int"],
            "sted_metode_kode" => ["sted_met_k", false, "int"],
            "sagsnr" => ["sagsnr", false, "varchar"],

            "geometri" => ["the_geom", true, "geometry", self::MULTILINESTRING],
        ],
        5601 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],
            "noegle" => ["noegle", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "link" => ["link", false, "varchar"],

            "h_daemp_kode" => ["h_daemp_k", true, "int"],
            "omfang_kode" => ["omfang_k", false, "int"],
            "hastighed_kode" => ["hastig_k", true, "int"],

            "foto_link" => ["foto_link", false, "varchar"],
            "foto_link1" => ["foto_link1", false, "varchar"],
            "foto_link2" => ["foto_link2", false, "varchar"],
            "foto_link3" => ["foto_link3", false, "varchar"],

            "geofafoto" => ["geofafoto", false, "varchar"],
            "geofafoto1" => ["geofafoto1", false, "varchar"],
            "geofafoto2" => ["geofafoto2", false, "varchar"],
            "geofafoto3" => ["geofafoto3", false, "varchar"],

            "geometri" => ["the_geom", true, "geometry", self::MULTIPOINT],
        ],
        5602 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],
            "noegle" => ["noegle", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "link" => ["link", false, "varchar"],
            "link1" => ["link1", false, "varchar"],

            "p_type_kode" => ["p_ty_k", true, "int"],
            "p_zone_nr" => ["p_zone_nr", false, "varchar"],
            "omraade" => ["omraade", false, "varchar"],
            "p_tid_kode" => ["p_tid_k", false, "int"],
            "p_hverdag_start" => ["p_hv_st", false, "time"],
            "p_hverdag_slut" => ["p_hv_sl", false, "time"],
            "p_loerdag_start" => ["p_loer_st", false, "time"],
            "p_loerdag_slut" => ["p_loer_sl", false, "time"],
            "p_soendag_start" => ["p_soen_st", false, "time"],
            "p_soendag_slut" => ["p_soen_sl", false, "time"],
            "p_pris_time" => ["p_pris_tim", false, "double precision"],
            "p_pris_fri_startperiode" => ["p_pris_fri", false, "int"],
            "p_start_betalingsperiode_hverdag" => ["p_stbet_hv", false, "time"],
            "p_slut_betalingsperiode_hverdag" => ["p_slbet_hv", false, "time"],
            "p_start_betalingsperiode_loerdag" => ["p_stbet_lo", false, "time"],
            "p_slut_betalingsperiode_loerdag" => ["p_slbet_lo", false, "time"],
            "p_start_betalingsperiode_soendag" => ["p_stbet_so", false, "time"],
            "p_slut_betalingsperiode_soendag" => ["p_slbet_so", false, "time"],
            "p_pladser_personbil" => ["plads_pbil", false, "int"],
            "p_pladser_handicap" => ["plads_hand", false, "int"],
            "p_pladser_elbil" => ["plads_ebil", false, "int"],
            "p_pladser_delebil" => ["plads_dele", false, "int"],
            "p_pladser_lastbil" => ["plads_last", false, "int"],
            "p_pladser_mc" => ["plads_mc", false, "int"],
            "p_pladser_erhverv" => ["plads_erhv", false, "int"],
            "p_plads_taxaholdeplads" => ["plads_taxa", false, "int"],
            "p_pladser_cykel" => ["plads_cyke", false, "int"],
            "p_pladser_ladcykel" => ["plads_ladc", false, "int"],
            "p_pladser_cykel_aflaast" => ["plads_c_af", false, "int"],
            "p_pladser_cykel_overdaekket" => ["plads_c_ov", false, "int"],
            "vejkode" => ["vejkode", false, "int"],
            "husnr" => ["husnr", false, "varchar"],
            "postnr" => ["postnr", false, "int"],
            "adr_id" => ["adr_id", false, "uuid"],
            "koordinat_north" => ["koord_n", false, "varchar"],
            "koordinat_east" => ["koord_e", false, "varchar"],

            "geometri" => ["the_geom", true, "geometry", self::MULTIPOLYGON],
        ],
        5603 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],
            "noegle" => ["noegle", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "link" => ["link", false, "varchar"],

            "hastighed_kode" => ["hastig_k", true, "int"],
            "tavle_nr" => ["tavle_nr", false, "varchar"],
            "hastighed_art_kode" => ["hast_art_k", false, "int"],

            "geometri" => ["the_geom", true, "geometry", self::MULTIPOLYGON],
        ],
        5604 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],
            "noegle" => ["noegle", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "link" => ["link", false, "varchar"],

            "regulerings_type_kode" => ["regul_ty_k", true, "int"],
            "tilladt_periode_bil" => ["tillad_bil", false, "varchar"],
            "tilladt_periode_cykel" => ["tillad_cyk", false, "varchar"],
            "tilladt_periode_varekoersel" => ["tillad_var", false, "varchar"],
            "cvf_adm_vejnr" => ["adm_vejnr", false, "int"],
            "frakm" => ["frakm", false, "int"],
            "fram" => ["fram", false, "int"],
            "tilkm" => ["tilkm", false, "int"],
            "tilm" => ["tilm", false, "int"],
            "sted_metode_kode" => ["sted_met_k", false, "int"],

            "geometri" => ["the_geom", true, "geometry", self::MULTILINESTRING],
        ],
        5605 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],
            "noegle" => ["noegle", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "link" => ["link", false, "varchar"],

            "dekl_type_kode" => ["dekl_ty_k", true, "int"],
            "vejkode" => ["vejkode", false, "int"],
            "cvf_vejkode" => ["cvf_vejkode", false, "varchar"],
            "dekl_link" => ["dekl_link", false, "varchar"],
            "bredde" => ["bredde", false, "int"],
            "forskydning" => ["forskydnin", false, "double precision"],
            "sagsnr" => ["sagsnr", false, "varchar"],

            "geometri" => ["the_geom", true, "geometry", self::MULTIPOLYGON],
        ],
        5606 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],
            "noegle" => ["noegle", false, "varchar"],
            "note" => ["note", false, "varchar"],

            "inventar_nr" => ["inventar_nr", false, "varchar"],
            "inventar_type_kode" => ["inven_ty_k", true, "int"],
            "model" => ["model", false, "varchar"],
            "tilstand_kode" => ["tilstand_k", false, "int"],

            "foto_link" => ["foto_link", false, "varchar"],
            "foto_link1" => ["foto_link1", false, "varchar"],
            "foto_link2" => ["foto_link2", false, "varchar"],
            "foto_link3" => ["foto_link3", false, "varchar"],

            "geofafoto" => ["geofafoto", false, "varchar"],
            "geofafoto1" => ["geofafoto1", false, "varchar"],
            "geofafoto2" => ["geofafoto2", false, "varchar"],
            "geofafoto3" => ["geofafoto3", false, "varchar"],

            "geometri" => ["the_geom", true, "geometry", self::MULTIPOINT],
        ],
        5611 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],
            "noegle" => ["noegle", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "link" => ["link", false, "varchar"],

            "rute_nr" => ["rute_nr", false, "varchar"],
            "rute_navn" => ["rute_navn", false, "varchar"],
            "rutetype_kode" => ["rute_typ_k", false, "int"],
            "cvr_opslag" => ["cvr_opslag", false, "varchar"],
            "vinterentreprenoer" => ["vi_ent", false, "varchar"],
            "rute_nr_sne" => ["rute_nrsne", false, "varchar"],
            "rute_entreprenoer_salt" => ["rute_e_sal", false, "varchar"],
            "rute_nr_salt" => ["rute_nrsal", false, "varchar"],

            "geometri" => ["the_geom", true, "geometry", self::MULTILINESTRING],
        ],
        5612 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],
            "noegle" => ["noegle", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "link" => ["link", false, "varchar"],

            "vinterserviceomraade_kode" => ["v_servi_k", false, "int"],
            "vinterservice_nr" => ["v_servi", false, "varchar"],
            "vinterservice_navn" => ["v_servi_na", false, "varchar"],
            "rute_nr" => ["rute_nr", false, "varchar"],
            "rute_navn" => ["rute_na", false, "varchar"],
            "vinterservice_beskrivelse" => ["vinter_besk", false, "varchar"],
            "areal" => ["areal", false, "int"],
            "norm_tid" => ["norm_tid", false, "int"],

            "geometri" => ["the_geom", true, "geometry", self::MULTIPOLYGON],
        ],
        5613 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],
            "noegle" => ["noegle", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "link" => ["link", false, "varchar"],

            "p_brug_kode" => ["p_brug_k", true, "int"],
            "p_brug_tekst" => ["p_brug_txt", false, "varchar"],
            "p_antal" => ["p_antal", false, "int"],
            "p_zone_nr" => ["p_zone_nr", false, "varchar"],
            "omraade" => ["omraade", false, "varchar"],

            "geometri" => ["the_geom", true, "geometry", self::MULTIPOLYGON],
        ],
        5614 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],
            "noegle" => ["noegle", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "link" => ["link", false, "varchar"],

            "stationerings_nr" => ["station_nr", false, "int"],
            "stationerings_beskrivelse" => ["statio_bes", false, "varchar"],

            "geometri" => ["the_geom", true, "geometry", self::MULTIPOINT],
        ],
        6800 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],
            "noegle" => ["noegle", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "link" => ["link", false, "varchar"],

            "vedlhold_f_type_kode" => ["f_typ_kode", true, "int"],
            "biodiversitet" => ["biodivers", false, "varchar"],
            "arbejdssted" => ["arb_sted", false, "varchar"],
            "konto_nr" => ["konto_nr", false, "varchar"],
            "cvr_opslag" => ["cvr_opslag", false, "varchar"],
            "udfoerer_entrep" => ["udf_entrep", false, "varchar"],
            "udbyder_kontakt" => ["udbyder", false, "varchar"],
            "sagsnr" => ["sagsnr", false, "varchar"],
            "anlaegsaar" => ["anlaegsaar", false, "date"],
            "etabl_pleje_udloeb" => ["etab_udlob", false, "date"],
            "udskiftningaar" => ["udskift", false, "date"],
            "udtyndaar" => ["udtynd", false, "date"],
            "hoejde" => ["hoejde", false, "double precision"],
            "bredde" => ["bredde", false, "double precision"],
            "laengde" => ["laengde", false, "double precision"],
            "diameter" => ["diameter", false, "double precision"],
            "areal" => ["areal", false, "double precision"],
            "klip_sider" => ["klip_sider", false, "int"],
            "klip_flade" => ["klip_flade", false, "double precision"],
            "iot_enhed" => ["io_enhed", false, "varchar"],
            "iot_maaling" => ["iot_maal", false, "varchar"],
            "driftniv_kode" => ["driftniv_k", false, "int"],
            "ukrudtsbek_kode" => ["ukrudt_k", false, "int"],
            "tilstand_kode" => ["tilstand_k", false, "int"],
            "tilstand_dato" => ["tilst_dato", false, "date"],
            "vejkode" => ["vejkode", false, "int"],

            "foto_link" => ["foto_link", false, "varchar"],
            "foto_link1" => ["foto_link1", false, "varchar"],
            "foto_link2" => ["foto_link2", false, "varchar"],
            "foto_link3" => ["foto_link3", false, "varchar"],

            "geofafoto" => ["geofafoto", false, "varchar"],
            "geofafoto1" => ["geofafoto1", false, "varchar"],
            "geofafoto2" => ["geofafoto2", false, "varchar"],
            "geofafoto3" => ["geofafoto3", false, "varchar"],

            "geometri" => ["the_geom", true, "geometry", self::MULTIPOLYGON],
        ],
        6801 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],
            "noegle" => ["noegle", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "link" => ["link", false, "varchar"],

            "vedlhold_l_type_kode" => ["l_typ_kode", true, "int"],
            "biodiversitet" => ["biodivers", false, "varchar"],
            "arbejdssted" => ["arb_sted", false, "varchar"],
            "konto_nr" => ["konto_nr", false, "varchar"],
            "cvr_opslag" => ["cvr_opslag", false, "varchar"],
            "udfoerer_entrep" => ["udf_entrep", false, "varchar"],
            "udbyder_kontakt" => ["udbyder", false, "varchar"],
            "sagsnr" => ["sagsnr", false, "varchar"],
            "anlaegsaar" => ["anlaegsaar", false, "date"],
            "etabl_pleje_udloeb" => ["etab_udlob", false, "date"],
            "udskiftningaar" => ["udskift", false, "date"],
            "hoejde" => ["hoejde", false, "double precision"],
            "bredde" => ["bredde", false, "double precision"],
            "laengde" => ["laengde", false, "double precision"],
            "diameter" => ["diameter", false, "double precision"],
            "areal" => ["areal", false, "double precision"],
            "klip_flade" => ["klip_flade", false, "double precision"],
            "klip_sider" => ["klip_sider", false, "int"],
            "iot_enhed" => ["io_enhed", false, "varchar"],
            "iot_maaling" => ["iot_maal", false, "varchar"],
            "driftniv_kode" => ["driftniv_k", false, "int"],
            "ukrudtsbek_kode" => ["ukrudt_k", false, "int"],
            "tilstand_kode" => ["tilstand_k", false, "int"],
            "tilstand_dato" => ["tilst_dato", false, "date"],
            "vejkode" => ["vejkode", false, "int"],

            "foto_link" => ["foto_link", false, "varchar"],
            "foto_link1" => ["foto_link1", false, "varchar"],
            "foto_link2" => ["foto_link2", false, "varchar"],
            "foto_link3" => ["foto_link3", false, "varchar"],

            "geofafoto" => ["geofafoto", false, "varchar"],
            "geofafoto1" => ["geofafoto1", false, "varchar"],
            "geofafoto2" => ["geofafoto2", false, "varchar"],
            "geofafoto3" => ["geofafoto3", false, "varchar"],

            "geometri" => ["the_geom", true, "geometry", self::MULTILINESTRING],
        ],
        6802 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],
            "noegle" => ["noegle", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "link" => ["link", false, "varchar"],

            "vedlhold_p_type_kode" => ["f_typ_kode", true, "int"],
            "biodiversitet" => ["biodivers", false, "varchar"],
            "arbejdssted" => ["arb_sted", false, "varchar"],
            "konto_nr" => ["konto_nr", false, "varchar"],
            "cvr_opslag" => ["cvr_opslag", false, "varchar"],
            "udfoerer_entrep" => ["udf_entrep", false, "varchar"],
            "udbyder_kontakt" => ["udbyder", false, "varchar"],
            "sagsnr" => ["sagsnr", false, "varchar"],
            "froeaar" => ["froeaar", false, "date"],
            "anlaegsdato" => ["anlaeg_dato", false, "date"],
            "etabl_pleje_udloeb" => ["etab_udlob", false, "date"],
            "udskiftningsdato" => ["udskift", false, "date"],
            "hoejde" => ["hoejde", false, "double precision"],
            "bredde" => ["bredde", false, "double precision"],
            "laengde" => ["laengde", false, "double precision"],
            "diameter" => ["diameter", false, "double precision"],
            "areal" => ["areal", false, "double precision"],
            "omkreds" => ["omkreds", false, "double precision"],
            "klip_flade" => ["klip_flade", false, "double precision"],
            "klip_sider" => ["klip_sider", false, "int"],
            "iot_enhed" => ["io_enhed", false, "varchar"],
            "iot_maaling" => ["iot_maal", false, "varchar"],
            "driftniv_kode" => ["driftniv_k", false, "int"],
            "ukrudtsbek_kode" => ["ukrudt_k", false, "int"],
            "tilstand_kode" => ["tilstand_k", false, "int"],
            "tilstand_dato" => ["tilst_dato", false, "date"],
            "vejkode" => ["vejkode", false, "int"],
            "traebetegn_kode" => ["traebetegn_kode", false, "int"],
            "traeart_sort_suppl" => ["traeart_sort_suppl", false, "varchar"],
            "bevaringsvaerdig_kode" => ["bevar_k", false, "int"],
            "tilsynstrae_kode" => ["tilsyn_k", false, "int"],
            "livsfase_kode" => ["livsfase_kode", false, "int"],

            "foto_link" => ["foto_link", false, "varchar"],
            "foto_link1" => ["foto_link1", false, "varchar"],
            "foto_link2" => ["foto_link2", false, "varchar"],
            "foto_link3" => ["foto_link3", false, "varchar"],

            "geofafoto" => ["geofafoto", false, "varchar"],
            "geofafoto1" => ["geofafoto1", false, "varchar"],
            "geofafoto2" => ["geofafoto2", false, "varchar"],
            "geofafoto3" => ["geofafoto3", false, "varchar"],

            "geometri" => ["the_geom", true, "geometry", self::MULTIPOINT],
        ],
        6803 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],
            "noegle" => ["noegle", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "link" => ["link", false, "varchar"],

            "pg_distrikt_kode" => ["pg_distr_k", true, "int"],
            "pg_fagentreprise_kode" => ["pg_fagen_k", false, "int"],
            "pg_distrikt_nr" => ["pg_dist_nr", false, "varchar"],
            "pg_distrikt_navn" => ["pg_dist_nv", false, "varchar"],
            "ansvarlig" => ["ansvarlig", false, "varchar"],
            "konto_nr" => ["konto_nr", false, "varchar"],
            "cvr_opslag" => ["cvr_opslag", false, "varchar"],
            "udfoerer" => ["udfoerer", false, "varchar"],
            "sagsnr" => ["sagsnr", false, "varchar"],
            "udfoerer_kontakt1" => ["udf_kont_1", false, "varchar"],
            "udfoerer_kontakt2" => ["udf_kont_2", false, "varchar"],
            "udbyder_kontakt" => ["udbyd_kont", false, "varchar"],
            "vejkode" => ["vejkode", false, "int"],
            "cvf_vejkode" => ["cvf_vejkode", false, "varchar"],
            "husnr" => ["husnr", false, "varchar"],
            "postnr" => ["postnr", false, "int"],
            "adr_id" => ["adr_id", false, "uuid"],

            "foto_link" => ["foto_link", false, "varchar"],
            "foto_link1" => ["foto_link1", false, "varchar"],
            "foto_link2" => ["foto_link2", false, "varchar"],
            "foto_link3" => ["foto_link3", false, "varchar"],

            "geofafoto" => ["geofafoto", false, "varchar"],
            "geofafoto1" => ["geofafoto1", false, "varchar"],
            "geofafoto2" => ["geofafoto2", false, "varchar"],
            "geofafoto3" => ["geofafoto3", false, "varchar"],

            "geometri" => ["the_geom", true, "geometry", self::MULTIPOLYGON],
        ],
        5300 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],
            "noegle" => ["noegle", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "link" => ["link", false, "varchar"],

            "gyldig_fra" => ["gyldig_fra", true, "date"],
            "funktion" => ["funktion", true, "varchar"],
            "planlagt_aktivitet" => ["planl_akti", true, "varchar"],
            "genoptaget" => ["genoptaget", true, "date"],
            "kommentar" => ["kommentar", false, "varchar"],
            "sagsnr" => ["sagsnr", false, "varchar"],

            "geometri" => ["the_geom", true, "geometry", self::MULTIPOLYGON],
        ],

        5104 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],
            "noegle" => ["noegle", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "link" => ["link", false, "varchar"],

            "invasivart_kode" => ["invasiv_k", true, "int"],
            "inventoer" => ["inventoer", true, "varchar"],
            "indberetning_sagsnr" => ["indb_sagsnr", false, "varchar"],
            "observationsdato" => ["obs_dato", false, "date"],
            "start_antal_kode" => ["st_ant_k", false, "int"],
            "start_udbredelse" => ["st_udbred", false, "int"],
            "seneste_tilsyn_dato" => ["sen_dato", false, "date"],
            "seneste_tilsyn_antal_kode" => ["sen_ant_k", false, "int"],
            "seneste_tilsyn_udbredelse" => ["sen_udbred", false, "int"],
            "lokalitet" => ["lokalitet", false, "int"],
            "ia_status_kode" => ["status_k", false, "int"],
            "forekomst" => ["forekomst", false, "varchar"],
            "bekaemp" => ["bekaemp", false, "varchar"],
            "sagsnr" => ["sagsnr", false, "varchar"],

            "foto_link" => ["foto_link", false, "varchar"],
            "foto_link1" => ["foto_link1", false, "varchar"],
            "foto_link2" => ["foto_link2", false, "varchar"],
            "foto_link3" => ["foto_link3", false, "varchar"],

            "geometri" => ["the_geom", true, "geometry", self::MULTIPOLYGON],
        ],
        5106 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],
            "noegle" => ["noegle", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "link" => ["link", false, "varchar"],

            "pleje_type_kode" => ["pleje_ty_k", true, "int"],
            "omr_nr" => ["omr_nr", false, "int"],
            "omr_navn" => ["omr_navn", false, "varchar"],
            "fortidsmindenr" => ["fortidsmnr", false, "varchar"],
            "facilitet_kode" => ["facilite_k", false, "int"],
            "aftale_type" => ["aftale_ty", false, "varchar"],
            "gyldig_fra" => ["gyldig_fra", true, "date"],
            "gyldig_til" => ["gyldig_til", false, "date"],
            "ejerstatus_kode" => ["ejerstat_k", false, "int"],
            "sagsnr" => ["sagsnr", false, "varchar"],
            "projekt_type" => ["projekt_ty", false, "varchar"],
            "dyrehold" => ["dyrehold", true, "varchar"],
            "antal_moder" => ["antal_mode", false, "int"],
            "chr" => ["chr", false, "int"],
            "cvr_opslag" => ["cvr_opslag", false, "varchar"],
            "navn" => ["navn", false, "varchar"],
            "telefon" => ["telefon", false, "int"],
            "mobil" => ["mobil", false, "int"],
            "mail" => ["mail", false, "varchar"],
            "ajour" => ["ajour", false, "date"],

            "geometri" => ["the_geom", true, "geometry", self::MULTIPOLYGON],
        ],

        5107 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],
            "noegle" => ["noegle", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "link" => ["link", false, "varchar"],

            "invasivart_kode" => ["invasiv_k", true, "int"],
            "inventoer" => ["inventoer", true, "varchar"],
            "indberetning_sagsnr" => ["indb_sagsnr", false, "varchar"],
            "observationsdato" => ["obs_dato", false, "date"],
            "start_antal_kode" => ["st_ant_k", false, "int"],
            "start_udbredelse" => ["st_udbred", false, "int"],
            "seneste_tilsyn_dato" => ["sen_dato", false, "date"],
            "seneste_tilsyn_antal_kode" => ["sen_ant_k", false, "int"],
            "seneste_tilsyn_udbredelse" => ["sen_udbred", false, "int"],
            "lokalitet" => ["lokalitet", false, "int"],
            "ia_status_kode" => ["status_k", false, "int"],
            "forekomst" => ["forekomst", false, "varchar"],
            "bekaemp" => ["bekaemp", false, "varchar"],
            "sagsnr" => ["sagsnr", false, "varchar"],

            "foto_link" => ["foto_link", false, "varchar"],
            "foto_link1" => ["foto_link1", false, "varchar"],
            "foto_link2" => ["foto_link2", false, "varchar"],
            "foto_link3" => ["foto_link3", false, "varchar"],

            "geometri" => ["the_geom", true, "geometry", self::MULTIPOINT],
        ],

        5200 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],
            "noegle" => ["noegle", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "link" => ["link", false, "varchar"],

            "affald_prod_kode" => ["affald_pr_k", true, "int"],
            "cvr_opslag" => ["cvr_opslag", false, "varchar"],
            "navn" => ["navn", true, "varchar"],
            "ejendoms_nr" => ["ejd_nr", true, "int"],
            "vejkode" => ["vejkode", false, "int"],
            "cvf_vejkode" => ["cvf_vejkode", false, "varchar"],
            "husnr" => ["husnr", false, "varchar"],
            "postnr" => ["postnr", false, "int"],
            "adr_id" => ["adr_id", false, "uuid"],
            "markblok" => ["markblok", false, "varchar"],
            "marknummer" => ["mark_nr", false, "varchar"],
            "dosering_toerstof" => ["dose_toers", false, "double precision"],
            "dosering_vaadvaegt" => ["dose_vaadv", false, "double precision"],
            "fosfor_total" => ["fosfor_tot", false, "double precision"],
            "fosfor_udnyttelse" => ["fosfor_udn", false, "double precision"],
            "kvaelstof_total" => ["kvaels_tot", false, "double precision"],
            "kvaelstof_udnyttelse" => ["kvaels_udn", false, "double precision"],
            "kalium_total" => ["kalium_tot", false, "double precision"],
            "udbringning_aar" => ["udbrin_aar", false, "double precision"],
            "sagsnr" => ["sagsnr", false, "varchar"],

            "geometri" => ["the_geom", true, "geometry", self::MULTIPOLYGON],
        ],
        5400 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],
            "noegle" => ["noegle", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "link" => ["link", false, "varchar"],

            "gyldig_fra" => ["gyldig_fra", true, "date"],
            "gyldig_til" => ["gyldig_til", false, "date"],
            "affalddistrikt_nr" => ["aff_dis_nr", false, "int"],
            "affalddistrikt_navn" => ["aff_dis_na", false, "varchar"],
            "affaldstype_kode" => ["aff_type_k", false, "int"],
            "afh_frekvens" => ["afh_frekv", false, "varchar"],
            "afh_dag" => ["afh_dag", false, "varchar"],
            "cvr_opslag" => ["cvr_opslag", false, "varchar"],

            "geometri" => ["the_geom", true, "geometry", self::MULTIPOLYGON],
        ],
        5401 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],
            "noegle" => ["noegle", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "link" => ["link", false, "varchar"],

            "gs_navn" => ["gs_navn", false, "varchar"],
            "gs_type_kode" => ["gs_type_k", true, "int"],
            "p_nr" => ["p_nr", false, "varchar"],
            "vejkode" => ["vejkode", false, "int"],
            "cvf_vejkode" => ["cvf_vejkode", false, "varchar"],
            "husnr" => ["husnr", false, "varchar"],
            "postnr" => ["postnr", false, "int"],
            "adr_id" => ["adr_id", false, "uuid"],
            "sagsnr" => ["sagsnr", false, "varchar"],

            "geometri" => ["the_geom", true, "geometry", self::MULTIPOINT],
        ],
        5402 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],
            "noegle" => ["noegle", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "link" => ["link", false, "varchar"],

            "gc_type_kode" => ["gc_type_k", false, "int"],
            "model" => ["model", false, "varchar"],
            "nedgravet" => ["nedgravet", false, "boolean"],
            "t_frekvens" => ["t_frekvens", false, "varchar"],
            "t_dato" => ["t_dato", false, "date"],
            "sagsnr" => ["sagsnr", false, "varchar"],

            "geometri" => ["the_geom", true, "geometry", self::MULTIPOINT],
        ],
        5506 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],
            "noegle" => ["noegle", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "link" => ["link", false, "varchar"],

            "anlaeg_type_kode" => ["anlaeg_t_k", true, "int"],
            "punkt_nr" => ["punkt_nr", false, "varchar"],
            "oplandstype" => ["opl_type", false, "varchar"],
            "recipient" => ["recipient", false, "varchar"],
            "anlaegsstatus_kode" => ["anl_stat_k", false, "int"],
            "planstatus_kode" => ["anl_status", true, "int"],

            "geometri" => ["the_geom", true, "geometry", self::MULTIPOINT],
        ],

        5902 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],
            "noegle" => ["noegle", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "link" => ["link", false, "varchar"],

            "brine_maengde" => ["brine_mgd", false, "int"],
            "brine_blandingsforhold" => ["brine_bl", false, "varchar"],
            "strenge_antal" => ["stre_antal", false, "int"],
            "strenge_laengde_samlede" => ["stre_laeng", false, "int"],
            "tilladelses_dato" => ["tilla_dato", false, "date"],
            "faerdigmeldingsdato" => ["faerd_dato", false, "date"],
            "vaesketype_kode" => ["vaeskety_k", false, "int"],
            "gyldig_fra" => ["gyldig_fra", true, "date"],
            "gyldig_til" => ["gyldig_til", false, "date"],
            "sagsnr" => ["sagsnr", false, "varchar"],
            "sag_status_kode" => ["sag_stat_k", false, "int"],

            "geometri" => ["the_geom", true, "geometry", self::MULTIPOLYGON],
        ],

        6200 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],
            "noegle" => ["noegle", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "link" => ["link", false, "varchar"],

            "data_oprindelse" => ["data_oprindelse", false, "varchar"],
            "omraade_nr" => ["omr_nr", false, "int"],
            "geologi_kode" => ["geologi_k", true, "int"],
            "jordtype_kode" => ["jord_ty_k", true, "int"],
            "terraen_kode" => ["terraen_k", true, "int"],
            "kompleksitet_kode" => ["kompleks_k", true, "int"],
            "vandelement" => ["vand_elem", false, "varchar"],
            "farvandsomraade" => ["farvand_om", false, "varchar"],
            "strandbred" => ["strandbred", false, "varchar"],
            "begrund_afgraensning" => ["afgraens", false, "varchar"],
            "omr_sammenhaeng" => ["omr_sam", false, "varchar"],
            "link1" => ["link1", false, "varchar"],

            "geometri" => ["the_geom", true, "geometry", self::MULTIPOLYGON],
        ],
        6201 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],
            "noegle" => ["noegle", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "link" => ["link", false, "varchar"],

            "data_oprindelse" => ["data_opr", false, "varchar"],
            "omraade_nr" => ["omr_nr", false, "int"],
            "begrund_afgraensning" => ["afgraens", true, "varchar"],

            "link1" => ["link1", false, "varchar"],
            "link2" => ["link2", false, "varchar"],
            "link3" => ["link3", false, "varchar"],

            "geometri" => ["the_geom", true, "geometry", self::MULTIPOLYGON],
        ],
        6202 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],
            "noegle" => ["noegle", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "link" => ["link", false, "varchar"],

            "omraade_nr" => ["omr_nr", false, "int"],
            "dato_besigtig" => ["besigt_dat", false, "date"],
            "navn_besigtig" => ["besigt_nv", false, "varchar"],
            "rev_dato" => ["rev_dato", false, "date"],
            "landskabskarakter" => ["landskab_b", true, "varchar"],
            "tidsdybde_kode" => ["tidsdyb_k", false, "int"],
            "tidsdybde_beskr" => ["tidsdyb_b", false, "varchar"],
            "intakthed_kode" => ["intakt_k", true, "int"],
            "intakthed_beskr" => ["intakt_b", false, "varchar"],
            "noeglefunktion" => ["noeglefunk", false, "varchar"],
            "afgr_naboomr" => ["afg_nabo", false, "varchar"],
            "skala_kode" => ["skala_k", false, "int"],
            "skala_beskrivelse" => ["skala_b", false, "varchar"],
            "rumlig_afgraensning_kode" => ["rum_afg_k", false, "int"],
            "rumlig_beskrivelse" => ["rum_besk", false, "varchar"],
            "kompleksitet_kode" => ["kompleks_k", false, "int"],
            "kompleksitet_beskrivelse" => ["kompleks_b", false, "varchar"],
            "struktur_kode" => ["struktur_k", false, "int"],
            "struktur_beskrivelse" => ["struktur_b", false, "varchar"],
            "visuel_uro_kode" => ["vis_uro_k", false, "int"],
            "visuel_uro_beskrivelse" => ["vis_uro_b", false, "varchar"],
            "kystforhold" => ["kyst_forh", false, "varchar"],
            "oplevelse" => ["oplevelse", false, "varchar"],

            "link1" => ["link1", false, "varchar"],
            "link2" => ["link2", false, "varchar"],

            "geometri" => ["the_geom", true, "geometry", self::MULTIPOLYGON],
        ],
        6203 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],
            "noegle" => ["noegle", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "link" => ["link", false, "varchar"],

            "omraade_nr" => ["omr_nr", false, "int"],
            "delomraade_nr" => ["delomr_nr", false, "varchar"],
            "karakterstyrke_kode" => ["kar_styr_k", true, "int"],
            "karakterstyrke_notat" => ["kar_styr_n", false, "varchar"],
            "visuel_notat" => ["visuel_n", false, "varchar"],
            "tilstand_kode" => ["tilst_k", false, "int"],
            "tilstand_notat" => ["tilst_n", false, "varchar"],
            "udvikling" => ["udvikling", false, "varchar"],
            "saarbarhed_kode" => ["saarbar_k", false, "int"],
            "saarbarhed_notat" => ["saarbar_n", false, "varchar"],
            "tiltag" => ["tiltag", false, "varchar"],

            "geometri" => ["the_geom", true, "geometry", self::MULTIPOLYGON],
        ],
        6122 => [
            "objekt_id" => ["objekt_id", false, "uuid"],
            "cvr_kode" => ["cvr_kode", true, "int"],
            "bruger_id" => ["bruger_id", true, "varchar"],
            "oprindkode" => ["oprindkode", true, "int"],
            "statuskode" => ["statuskode", true, "int"],
            "off_kode" => ["off_kode", true, "int"],
            "noegle" => ["noegle", false, "varchar"],
            "note" => ["note", false, "varchar"],
            "link" => ["link", false, "varchar"],

            "beskyt_rum_type_kode" => ["bes_r_k", true, "int"],
            "beskyt_rum_nr" => ["bes_r_nr", true, "varchar"],
            "matrikelejer" => ["mat_ejer", true, "varchar"],
            "udfoert_af" => ["udfoert_af", true, "varchar"],
            "udfoert_dato" => ["udfoert_da", true, "date"],
            "godkendt_af" => ["godkend_af", true, "varchar"],
            "godkendt_dato" => ["godkend_d", true, "date"],
            "dokumentation" => ["dokument", true, "bool"],
            "inspektioner" => ["inspektion", true, "bool"],
            "bbr" => ["bbr", true, "bool"],
            "lokaliseret" => ["lokalise", true, "bool"],
            "lokaliseret_aarsag" => ["lokalise_a", false, "varchar"],

            "adgang_kode" => ["adgang", false, "int"],
            "adgang_jordarbejde_kode" => ["adg_j", false, "int"],
            "adgang_gartnerarbejde_kode" => ["adg_g", false, "int"],
            "adgang_bygningsarbejde_kode" => ["adg_b", false, "int"],
            "beskyt_rum_anvendelse_kode" => ["bes_an_k", false, "int"],
            "antal_pladser" => ["antal_pl", false, "int"],
            "antal_opholdsrum" => ["ant_rum", false, "int"],
            "trapper_antal" => ["trap_ant", false, "int"],
            "adgangsdoerhuller_antal" => ["adg_ant", false, "int"],
            "adgangsdoerhuller_staal_kode" => ["adg_s", false, "int"],
            "adgangsdoerhuller_staal_funktion_kode" => ["adg_s_f", false, "int"],
            "noedudgange_antal" => ["noed_antal", false, "int"],
            "noedudgange_staallem_kode" => ["noed_lem", false, "int"],
            "taarn_kode" => ["taarn", false, "int"],
            "betondaeksel_kode" => ["b_daksel", false, "int"],
            "svanehals_kode" => ["svane", false, "int"],
            "vvs_sump_kode" => ["vvs_sump", false, "int"],
            "vvs_gulvafloeb_kode" => ["vvs_gulv", false, "int"],
            "vvs_sump_fungerer_kode" => ["vvs_s_fu", false, "int"],
            "fredstidsinstallationer_kode" => ["fred_ins", false, "int"],
            "note_fredstidsinstallationer" => ["note_fred", false, "varchar"],
            "note_konstruktion" => ["note_konst", false, "varchar"],
            "oevrig_teknisk_installationer_bemaerkninger" => ["oev_inst_b", false, "varchar"],
            "oevrig_bemaerkninger" => ["oev_bem", false, "varchar"],

            #1
            "_1_konstruktion_intakt_kode" => ["_1kon_in", false, "int"],
            "_1_konstruktion_blotlagt_armering_kode" => ["_1kon_ar", false, "int"],
            "_1_konstruktion_aendret_kode" => ["_1kon_ae", false, "int"],
            "_1_konstruktion_revner_gulv_kode" => ["_1kon_g", false, "int"],
            "_1_konstruktion_revner_vaegge_kode" => ["_1kon_v", false, "int"],
            "_1_konstruktion_revner_loft_kode" => ["_1kon_l", false, "int"],
            "_1_indtraengende_fugt_vand_kode" => ["_1i_fugt", false, "int"],
            "_1_vandpyt_gulv_kode" => ["_1vandpy", false, "int"],
            "_1_vand_daekker_gulv_kode" => ["_1vand_g", false, "int"],
            "_1_skadedyr_spor_kode" => ["_1dyr_sp", false, "int"],
            "_1_skadedyr_ekskrementer_kode" => ["_1dyr_ek", false, "int"],
            "_1_ventilation_haanddreven_kode" => ["_1v_haan", false, "int"],
            "_1_forbindelsesslanger_kode" => ["_1f_slan", false, "int"],
            "_1_indsugningsarrangementer_kode" => ["_1indsug", false, "int"],
            "_1_overtryksventiler_kode" => ["_1over_v", false, "int"],

            #2
            "_2_konstruktion_intakt_kode" => ["_2kon_in", false, "int"],
            "_2_konstruktion_blotlagt_armering_kode" => ["_2kon_ar", false, "int"],
            "_2_konstruktion_aendret_kode" => ["_2kon_ae", false, "int"],
            "_2_konstruktion_revner_gulv_kode" => ["_2kon_g", false, "int"],
            "_2_konstruktion_revner_vaegge_kode" => ["_2kon_v", false, "int"],
            "_2_konstruktion_revner_loft_kode" => ["_2kon_l", false, "int"],
            "_2_indtraengende_fugt_vand_kode" => ["_2i_fugt", false, "int"],
            "_2_vandpyt_gulv_kode" => ["_2vandpy", false, "int"],
            "_2_vand_daekker_gulv_kode" => ["_2vand_g", false, "int"],
            "_2_skadedyr_spor_kode" => ["_2dyr_sp", false, "int"],
            "_2_skadedyr_ekskrementer_kode" => ["_2dyr_ek", false, "int"],
            "_2_ventilation_haanddreven_kode" => ["_2v_haan", false, "int"],
            "_2_forbindelsesslanger_kode" => ["_2f_slan", false, "int"],
            "_2_indsugningsarrangementer_kode" => ["_2indsug", false, "int"],
            "_2_overtryksventiler_kode" => ["_2over_v", false, "int"],

            #3
            "_3_konstruktion_intakt_kode" => ["_3kon_in", false, "int"],
            "_3_konstruktion_blotlagt_armering_kode" => ["_3kon_ar", false, "int"],
            "_3_konstruktion_aendret_kode" => ["_3kon_ae", false, "int"],
            "_3_konstruktion_revner_gulv_kode" => ["_3kon_g", false, "int"],
            "_3_konstruktion_revner_vaegge_kode" => ["_3kon_v", false, "int"],
            "_3_konstruktion_revner_loft_kode" => ["_3kon_l", false, "int"],
            "_3_indtraengende_fugt_vand_kode" => ["_3i_fugt", false, "int"],
            "_3_vandpyt_gulv_kode" => ["_3vandpy", false, "int"],
            "_3_vand_daekker_gulv_kode" => ["_3vand_g", false, "int"],
            "_3_skadedyr_spor_kode" => ["_3dyr_sp", false, "int"],
            "_3_skadedyr_ekskrementer_kode" => ["_3dyr_ek", false, "int"],
            "_3_ventilation_haanddreven_kode" => ["_3v_haan", false, "int"],
            "_3_forbindelsesslanger_kode" => ["_3f_slan", false, "int"],
            "_3_indsugningsarrangementer_kode" => ["_3indsug", false, "int"],
            "_3_overtryksventiler_kode" => ["_3over_v", false, "int"],
            
            #3
            "_4_konstruktion_intakt_kode" => ["_4kon_in", false, "int"],
            "_4_konstruktion_blotlagt_armering_kode" => ["_4kon_ar", false, "int"],
            "_4_konstruktion_aendret_kode" => ["_4kon_ae", false, "int"],
            "_4_konstruktion_revner_gulv_kode" => ["_4kon_g", false, "int"],
            "_4_konstruktion_revner_vaegge_kode" => ["_4kon_v", false, "int"],
            "_4_konstruktion_revner_loft_kode" => ["_4kon_l", false, "int"],
            "_4_indtraengende_fugt_vand_kode" => ["_4i_fugt", false, "int"],
            "_4_vandpyt_gulv_kode" => ["_4vandpy", false, "int"],
            "_4_vand_daekker_gulv_kode" => ["_4vand_g", false, "int"],
            "_4_skadedyr_spor_kode" => ["_4dyr_sp", false, "int"],
            "_4_skadedyr_ekskrementer_kode" => ["_4dyr_ek", false, "int"],
            "_4_ventilation_haanddreven_kode" => ["_4v_haan", false, "int"],
            "_4_forbindelsesslanger_kode" => ["_4f_slan", false, "int"],
            "_4_indsugningsarrangementer_kode" => ["_4indsug", false, "int"],
            "_4_overtryksventiler_kode" => ["_4over_v", false, "int"],


            "geometri" => ["the_geom", true, "geometry", self::MULTIPOINT],
        ],
    ];
}
